-- MySQL Script generated by MySQL Workbench
-- 07/08/16 15:29:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cmlux
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cmlux` ;

-- -----------------------------------------------------
-- Schema cmlux
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cmlux` DEFAULT CHARACTER SET utf8 ;
USE `cmlux` ;

-- -----------------------------------------------------
-- Table `cmlux`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cmlux`.`role` ;

CREATE TABLE IF NOT EXISTS `cmlux`.`role` (
  `id` INT(11) NOT NULL,
  `rol_name` VARCHAR(45) NOT NULL,
  `rol_description` VARCHAR(45) NOT NULL,
  `rolecol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `rol_name_UNIQUE` (`rol_name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Définition des droits d\'accès aux différents formulaires et insertions données';


-- -----------------------------------------------------
-- Table `cmlux`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cmlux`.`users` ;

CREATE TABLE IF NOT EXISTS `cmlux`.`users` (
  `id` INT(11) NOT NULL,
  `use_userName` VARCHAR(45) NOT NULL,
  `use_name` VARCHAR(45) NOT NULL,
  `use_firstName` VARCHAR(45) NOT NULL,
  `use_adress` VARCHAR(45) NOT NULL,
  `use_postCode` VARCHAR(45) NOT NULL,
  `use_phone` VARCHAR(45) NOT NULL,
  `use_fax` VARCHAR(45) NOT NULL,
  `use_email` VARCHAR(45) NOT NULL,
  `use_password` VARCHAR(45) NOT NULL,
  `use_role` VARCHAR(45) NULL DEFAULT NULL,
  `use_dateCreation` VARCHAR(45) NULL DEFAULT NULL,
  `use_type` VARCHAR(45) NULL DEFAULT NULL,
  `use_roleOpt1` VARCHAR(45) NULL DEFAULT NULL,
  `use_roleOpt2` VARCHAR(45) NULL DEFAULT NULL,
  `role_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `role_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `use_userName_UNIQUE` (`use_userName` ASC),
  UNIQUE INDEX `use_email_UNIQUE` (`use_email` ASC),
  INDEX `fk_users_role_idx` (`role_id` ASC),
  CONSTRAINT `fk_users_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `cmlux`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tables pour l\'inscription des participants, représentants ou demandeurs pour des exposants ou sponsors';


-- -----------------------------------------------------
-- Table `cmlux`.`contenus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cmlux`.`contenus` ;

CREATE TABLE IF NOT EXISTS `cmlux`.`contenus` (
  `id` INT(11) NOT NULL,
  `con_type` VARCHAR(45) NOT NULL,
  `con_title` VARCHAR(45) NOT NULL,
  `con_dateStart` VARCHAR(45) NOT NULL,
  `con_dateEnd` VARCHAR(45) NOT NULL,
  `con_synopsis` VARCHAR(45) NOT NULL,
  `con_description` VARCHAR(45) NULL DEFAULT NULL,
  `con_avatar` VARCHAR(45) NOT NULL,
  `con_gallery` VARCHAR(45) NULL DEFAULT NULL,
  `users_id` INT(11) NOT NULL,
  `users_role_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `users_id`, `users_role_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_contenus_users1_idx` (`users_id` ASC, `users_role_id` ASC),
  CONSTRAINT `fk_contenus_users1`
    FOREIGN KEY (`users_id` , `users_role_id`)
    REFERENCES `cmlux`.`users` (`id` , `role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Données concernant les informations pour les news, events et reportages';


-- -----------------------------------------------------
-- Table `cmlux`.`typ_exposants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cmlux`.`typ_exposants` ;

CREATE TABLE IF NOT EXISTS `cmlux`.`typ_exposants` (
  `id` INT(11) NOT NULL,
  `typ_expo_name` VARCHAR(45) NOT NULL,
  `typ_spon_description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `typ_expo_name_UNIQUE` (`typ_expo_name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cmlux`.`exposants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cmlux`.`exposants` ;

CREATE TABLE IF NOT EXISTS `cmlux`.`exposants` (
  `id` INT(11) NOT NULL,
  `exp_userName` VARCHAR(45) NOT NULL,
  `exp_nameEposants` VARCHAR(45) NOT NULL,
  `exp_nameInCharge` VARCHAR(45) NOT NULL,
  `exp_firsNameInCharge` VARCHAR(45) NOT NULL,
  `exp_adress` VARCHAR(45) NOT NULL,
  `exp_city` VARCHAR(45) NOT NULL,
  `exp_postCode` VARCHAR(45) NOT NULL,
  `spo_Country` VARCHAR(45) NOT NULL,
  `exp_phone` VARCHAR(45) NOT NULL,
  `exp_mobile` VARCHAR(45) NULL DEFAULT NULL,
  `exp_fax` VARCHAR(45) NULL DEFAULT NULL,
  `exp_emailIncharge` VARCHAR(45) NOT NULL,
  `exp_emailGeneral` VARCHAR(45) NULL DEFAULT NULL,
  `exp_typeExposants` VARCHAR(45) NOT NULL,
  `exp_avatar` VARCHAR(45) NULL DEFAULT NULL,
  `exp_gallery` VARCHAR(45) NULL DEFAULT NULL,
  `exp__descriptionSponsors` VARCHAR(45) NULL DEFAULT NULL,
  `exp_url` VARCHAR(45) NULL DEFAULT NULL,
  `exp_pagote` VARCHAR(45) NULL DEFAULT NULL,
  `typ_exposants_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `typ_exposants_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_exposants_typ_exposants1_idx` (`typ_exposants_id` ASC),
  CONSTRAINT `fk_exposants_typ_exposants1`
    FOREIGN KEY (`typ_exposants_id`)
    REFERENCES `cmlux`.`typ_exposants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Données correspondant à toutes les données pour l\'exposant';


-- -----------------------------------------------------
-- Table `cmlux`.`galeries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cmlux`.`galeries` ;

CREATE TABLE IF NOT EXISTS `cmlux`.`galeries` (
  `id` INT(11) NOT NULL,
  `gal_name` VARCHAR(45) NOT NULL,
  `gal_path` VARCHAR(45) NOT NULL,
  `gal_legend` VARCHAR(45) NULL DEFAULT NULL,
  `gal_order` VARCHAR(45) NULL DEFAULT NULL,
  `gal_description` VARCHAR(45) NULL DEFAULT NULL,
  `users_id` INT(11) NOT NULL,
  `users_role_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `users_id`, `users_role_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `gal_name_UNIQUE` (`gal_name` ASC),
  INDEX `fk_galeries_users1_idx` (`users_id` ASC, `users_role_id` ASC),
  CONSTRAINT `fk_galeries_users1`
    FOREIGN KEY (`users_id` , `users_role_id`)
    REFERENCES `cmlux`.`users` (`id` , `role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'noms des galleries où seront liées aux photos';


-- -----------------------------------------------------
-- Table `cmlux`.`participants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cmlux`.`participants` ;

CREATE TABLE IF NOT EXISTS `cmlux`.`participants` (
  `id` INT(11) NOT NULL,
  `par_username` VARCHAR(45) NOT NULL,
  `par_name` VARCHAR(45) NOT NULL,
  `par_firstName` VARCHAR(45) NOT NULL,
  `par_adress` VARCHAR(45) NULL DEFAULT NULL,
  `par_city` VARCHAR(45) NULL DEFAULT NULL,
  `par_postCode` VARCHAR(45) NULL DEFAULT NULL,
  `par_country` VARCHAR(45) NULL DEFAULT NULL,
  `par_phone` VARCHAR(45) NOT NULL,
  `par_fax` VARCHAR(45) NULL DEFAULT NULL,
  `par_email` VARCHAR(45) NOT NULL,
  `par_avatar` VARCHAR(45) NULL DEFAULT NULL,
  `par_gallery` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `par_username_UNIQUE` (`par_username` ASC),
  UNIQUE INDEX `par_email_UNIQUE` (`par_email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Données cocnernant tous les particpants, privés, socitétés, ou autres, voulant exposer leurs voitures (une ou plusieur)';


-- -----------------------------------------------------
-- Table `cmlux`.`photos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cmlux`.`photos` ;

CREATE TABLE IF NOT EXISTS `cmlux`.`photos` (
  `id` INT(11) NOT NULL,
  `pho_name` VARCHAR(45) NULL DEFAULT NULL,
  `pho_path` VARCHAR(45) NOT NULL,
  `pho_legend` VARCHAR(45) NULL DEFAULT NULL,
  `pho_date` VARCHAR(45) NULL DEFAULT NULL,
  `phot_order` VARCHAR(45) NULL DEFAULT NULL,
  `galeries_id` INT(11) NOT NULL,
  `galeries_users_id` INT(11) NOT NULL,
  `galeries_users_role_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `galeries_id`, `galeries_users_id`, `galeries_users_role_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_photos_galeries1_idx` (`galeries_id` ASC, `galeries_users_id` ASC, `galeries_users_role_id` ASC),
  CONSTRAINT `fk_photos_galeries1`
    FOREIGN KEY (`galeries_id` , `galeries_users_id` , `galeries_users_role_id`)
    REFERENCES `cmlux`.`galeries` (`id` , `users_id` , `users_role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'liens de stockages photos';


-- -----------------------------------------------------
-- Table `cmlux`.`typ_sponsors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cmlux`.`typ_sponsors` ;

CREATE TABLE IF NOT EXISTS `cmlux`.`typ_sponsors` (
  `id` INT(11) NOT NULL,
  `typ_spon_name` VARCHAR(45) NOT NULL,
  `typ_spon_description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `typ_spon_name_UNIQUE` (`typ_spon_name` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cmlux`.`sponsors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cmlux`.`sponsors` ;

CREATE TABLE IF NOT EXISTS `cmlux`.`sponsors` (
  `id` INT(11) NOT NULL,
  `spo_userName` VARCHAR(45) NOT NULL,
  `spo_nameSponsors` VARCHAR(45) NOT NULL,
  `spo_nameInCharge` VARCHAR(45) NOT NULL,
  `spo_firsNameInCharge` VARCHAR(45) NOT NULL,
  `spo_adress` VARCHAR(45) NOT NULL,
  `spo_city` VARCHAR(45) NOT NULL,
  `spo_postCode` VARCHAR(45) NOT NULL,
  `spo_Country` VARCHAR(45) NOT NULL,
  `spo_phone` VARCHAR(45) NOT NULL,
  `spo_mobile` VARCHAR(45) NULL DEFAULT NULL,
  `spo_fax` VARCHAR(45) NULL DEFAULT NULL,
  `spo_emailIncharge` VARCHAR(45) NOT NULL,
  `spo_emailGeneral` VARCHAR(45) NULL DEFAULT NULL,
  `spo_typeSponsors` VARCHAR(45) NOT NULL,
  `spo_avatar` VARCHAR(45) NULL DEFAULT NULL,
  `spo_gallery` VARCHAR(45) NULL DEFAULT NULL,
  `spo_url` VARCHAR(45) NULL DEFAULT NULL,
  `typ_sponsors_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `typ_sponsors_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `spo_userName_UNIQUE` (`spo_userName` ASC),
  INDEX `fk_sponsors_typ_sponsors1_idx` (`typ_sponsors_id` ASC),
  CONSTRAINT `fk_sponsors_typ_sponsors1`
    FOREIGN KEY (`typ_sponsors_id`)
    REFERENCES `cmlux`.`typ_sponsors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Données reprennant toutes les informations concernant le sponsors et la personnne de contacte';


-- -----------------------------------------------------
-- Table `cmlux`.`users_has_sponsors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cmlux`.`users_has_sponsors` ;

CREATE TABLE IF NOT EXISTS `cmlux`.`users_has_sponsors` (
  `users_id` INT(11) NOT NULL,
  `users_role_id` INT(11) NOT NULL,
  `sponsors_id` INT(11) NOT NULL,
  PRIMARY KEY (`users_id`, `users_role_id`, `sponsors_id`),
  INDEX `fk_users_has_sponsors_sponsors1_idx` (`sponsors_id` ASC),
  INDEX `fk_users_has_sponsors_users1_idx` (`users_id` ASC, `users_role_id` ASC),
  CONSTRAINT `fk_users_has_sponsors_users1`
    FOREIGN KEY (`users_id` , `users_role_id`)
    REFERENCES `cmlux`.`users` (`id` , `role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_sponsors_sponsors1`
    FOREIGN KEY (`sponsors_id`)
    REFERENCES `cmlux`.`sponsors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cmlux`.`users_has_exposants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cmlux`.`users_has_exposants` ;

CREATE TABLE IF NOT EXISTS `cmlux`.`users_has_exposants` (
  `users_id` INT(11) NOT NULL,
  `users_role_id` INT(11) NOT NULL,
  `exposants_id` INT(11) NOT NULL,
  PRIMARY KEY (`users_id`, `users_role_id`, `exposants_id`),
  INDEX `fk_users_has_exposants_exposants1_idx` (`exposants_id` ASC),
  INDEX `fk_users_has_exposants_users1_idx` (`users_id` ASC, `users_role_id` ASC),
  CONSTRAINT `fk_users_has_exposants_users1`
    FOREIGN KEY (`users_id` , `users_role_id`)
    REFERENCES `cmlux`.`users` (`id` , `role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_exposants_exposants1`
    FOREIGN KEY (`exposants_id`)
    REFERENCES `cmlux`.`exposants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cmlux`.`users_has_participants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cmlux`.`users_has_participants` ;

CREATE TABLE IF NOT EXISTS `cmlux`.`users_has_participants` (
  `users_id` INT(11) NOT NULL,
  `users_role_id` INT(11) NOT NULL,
  `participants_id` INT(11) NOT NULL,
  PRIMARY KEY (`users_id`, `users_role_id`, `participants_id`),
  INDEX `fk_users_has_participants_participants1_idx` (`participants_id` ASC),
  INDEX `fk_users_has_participants_users1_idx` (`users_id` ASC, `users_role_id` ASC),
  CONSTRAINT `fk_users_has_participants_users1`
    FOREIGN KEY (`users_id` , `users_role_id`)
    REFERENCES `cmlux`.`users` (`id` , `role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_participants_participants1`
    FOREIGN KEY (`participants_id`)
    REFERENCES `cmlux`.`participants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
